version: '2'

volumes:
  orderer.shelbys.com:
  peer0.kshrd.com:
  peer0.subway.com:


networks:
  byfn:

services:
  orderer.shelbys.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer.shelbys.com
    container_name: orderer.shelbys.com
    networks:
      - byfn

  peer0.kshrd.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.kshrd.com
    container_name: peer0.kshrd.com
    networks:
      - byfn

  peer0.subway.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.subway.com
    container_name: peer0.subway.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:amd64-2.2
    tty: true
    stdin_open: true
    environment: 
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.kshrd.com:7051
      - CORE_PEER_LOCALMSPID=KshrdMSP
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/fabric-samples/shuru-network/crypto-config/peerOrganizations/shuru.shuru-network.com/peers/peer0.shuru.shuru-network.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/fabric-samples/shuru-network/crypto-config/peerOrganizations/shuru.shuru-network.com/peers/peer0.shuru.shuru-network.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/fabric-samples/shuru-network/crypto-config/peerOrganizations/beyond.shuru-network.com/peers/peer0.beyond.shuru-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/fabric-samples/shelbys/crypto-config/peerOrganizations/kshrd.com/users/Admin@kshrd.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../../chaincode/:/opt/gopath/src/chain
      - ../../crypto-config:/opt/gopath/fabric-samples/shelbys/crypto-config/
      - ../../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../../channel-artifacts:/opt/gopath/fabric-samples/shelbys/channel-artifacts
      - ../../:/opt/gopath/src/github.com/hyperledger/fabric/peer/config
    depends_on:
      - orderer.shelbys.com
      - peer0.kshrd.com
      - peer0.subway.com
    networks:
      - byfn