OrdererOrgs:
  - Name: ShelbysOrg
    Domain: shelbys.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: KshrdOrg
    Domain: kshrd.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
    Users:
      Count: 3
  - Name: SubwayOrg
    Domain: subway.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
    Users:
      Count: 3